In [7]:
from sklearn.datasets import load_iris
import numpy as np

In [6]:
iris = load_iris()
iris.data[0:2, :]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [9]:
x1 = np.array([[5.1], [3.5], [1.4], [0.2]])
x2 = np.array([[4.9], [3.0], [1.4], [0.2]])

print(x1)
print(x2)

[[5.1]
 [3.5]
 [1.4]
 [0.2]]
[[4.9]
 [3. ]
 [1.4]
 [0.2]]


In [15]:
X = np.array(iris.data[0:2, :])
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [16]:
X.T

array([[5.1, 4.9],
       [3.5, 3. ],
       [1.4, 1.4],
       [0.2, 0.2]])

### inner product

In [17]:
x = np.array([[1], [2], [3]])
y = np.array([[4], [5], [6]])

In [18]:
x.T @ y

array([[32]])

In [20]:
np.dot(x.T, y)

array([[32]])

In [21]:
#practice

stock_price = np.array([[100], [80], [50]])
stock_count = np.array([[3], [4], [5]])

np.dot(stock_count.T, stock_price)

array([[870]])