# dimension

In [8]:
arr = np.array(5)
arr

array(5)

In [9]:
arr.shape, arr.ndim

((), 0)

In [10]:
arr1 = np.array([1, 2, 3])
arr1

array([1, 2, 3])

In [11]:
arr1.shape, arr1.ndim

((3,), 1)

In [12]:
arr2 = np.array([[1, 2, 3]])
arr2

array([[1, 2, 3]])

In [13]:
arr2.shape, arr2.ndim

((1, 3), 2)

In [14]:
arr2_1 = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
arr2_1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [15]:
arr2_1.shape, arr2_1.ndim

((3, 3), 2)

In [16]:
arr4 = np.array([[[[1, 2, 3], [1, 2, 3], [1, 2, 3], [1, 2, 3]]]])
arr4

array([[[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]]]])

In [17]:
arr4.shape

(1, 1, 4, 3)

# Numpy basic

In [18]:
arr = np.array([[1, 2, 3], [1, 2, 3]])
arr.dtype

dtype('int64')

In [19]:
arr = np.array([[1, 2, 3], [1, 2, 3]], dtype=np.uint8)
arr.dtype

dtype('uint8')

In [20]:
len(arr)

2

In [21]:
arr.size

6

In [22]:
arr.shape

(2, 3)

## random

In [23]:
arr = np.random.randn(8, 8)
arr.shape

(8, 8)

In [24]:
arr = arr.reshape([32, 2])
arr.shape

(32, 2)

In [25]:
arr = arr.reshape(-1, 2, 1)
arr.shape

(32, 2, 1)

## ravel

In [26]:
arr = arr.ravel()
arr.shape

(64,)

## expand_dims

In [27]:
arr = np.expand_dims(arr, 0)
arr.shape

(1, 64)

In [28]:
arr = np.random.randn(8, 8)
arr.shape

(8, 8)

In [29]:
arr = arr.ravel()
arr.shape

(64,)

In [30]:
arr = np.expand_dims(arr, -1)
arr.shape

(64, 1)

In [31]:
arr = np.expand_dims(np.expand_dims(arr, -1), 0)
arr.shape

(1, 64, 1, 1)

## zeros & ones

In [32]:
zeros = np.zeros([3, 3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
ones * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [35]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [36]:
arr = np.arange(4, 9)
arr

array([4, 5, 6, 7, 8])

In [38]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## indexing

In [39]:
nums = [1, 2, 3, 4, 5]
nums[2]

3

In [41]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
arr[1]

array([3, 4, 5])

## slicing

In [42]:
 arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [43]:

arr[1:, 1:]

array([[4, 5],
       [7, 8]])

## boolean indexing

In [44]:
data = np.random.randn(3, 3)
data

array([[-0.85164244, -0.98161978,  0.7410975 ],
       [-0.45177825, -0.70717801, -0.24405533],
       [-0.13215878,  1.5869174 , -0.2251141 ]])

In [45]:
data <= 0

array([[ True,  True, False],
       [ True,  True,  True],
       [ True, False,  True]])

In [46]:
data[data <= 0] = 1

In [47]:
data

array([[1.       , 1.       , 0.7410975],
       [1.       , 1.       , 1.       ],
       [1.       , 1.5869174, 1.       ]])

## broadcast

In [48]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
arr + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [50]:
arr * 3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [51]:
arr + np.array([1, 1, 1])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## math function

In [69]:
arr_2 = np.random.randint(0, 2, size=(3, 3, 3))

In [70]:
arr, arr_2

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[[0, 0, 0],
         [1, 0, 0],
         [1, 0, 1]],
 
        [[1, 1, 1],
         [0, 0, 1],
         [1, 0, 0]],
 
        [[0, 1, 0],
         [1, 1, 1],
         [0, 1, 0]]]))

In [71]:
arr + arr_2

array([[[0, 1, 2],
        [4, 4, 5],
        [7, 7, 9]],

       [[1, 2, 3],
        [3, 4, 6],
        [7, 7, 8]],

       [[0, 2, 2],
        [4, 5, 6],
        [6, 8, 8]]])

In [75]:
np.sum(arr + arr_2, axis=0)

array([[ 1,  5,  7],
       [11, 13, 17],
       [20, 22, 25]])

In [74]:
np.sum(arr + arr_2)

121

In [76]:
np.max(arr + arr_2)

9

In [77]:
np.min(arr + arr_2)

0

In [78]:
np.mean(arr)

4.0

In [79]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [80]:
np.argmax(arr)

8

In [82]:
np.unique(arr_2)

array([0, 1])