# 1. What is Numpy?
<small>and how to use it? </small>

- numpy는 <b>"numerical python"</b>의 약자입니다.


- numpy는 다양한 머신러닝 라이브러리들에 의존성을 가지고 있고, 일반 파이썬 리스트에 비해 강력한 성능을 자랑합니다.


- python list와 비슷한 개념을 numpy에서는 **numpy array**라고 부른다.


- C언어와 JAVA에서 사용하는 array와 비슷한 개념이며, 동적 할당(dynamic type binding)을 지원하는 파이썬의 리스트와 구조가 다릅니다.


- Numpy의 특징
<br>
<br>

**1) numpy array는 모든 원소의 자료형이 동일해야 한다.**

(아래는 numpy array가 지원하는 data types)

![numpy_data_type](../images/numpy/numpy_datatypes.png)

**2) numpy array는 선언할 때 크기를 지정한 뒤, 변경할 수 없다. list.append(), pop()을 통해 자유롭게 원소 변경 및 크기 변경이 가능하지만, numpy array는 만들어지고 나면 원소의 update는 가능하지만, array의 크기를 변경할 수는 없다.**

**3) 사실 numpy array는 C, C++로 구현이 되어 있다. 이는 high performance를 내기 위해서이며, python이 Numerical computing에 취약하다는 단점을 보완한다.**

(아래 예시는 C언어와 파이썬의 코드 비교)

```C
/* C 코드 */
int result = 0;
for(int i=0; i<100; i++){
    result += i;
}
```

```python
# 파이썬 코드
result = 0
for i in range(100):
    result += i
```

**4) numpy array가 python list보다 빠른 이유 중에 하나는 원소의 type checking을 할 필요가 없기 때문이다.**

(아래 예시를 보자)

```C
/* C 코드 */
int x = 4;
x = "four";  // 실패
```
-> It is called, "Static type binding"



```python
# 파이썬 코드
x = 4
x = "four"
```

-> It is called, "Dynamic type binding"

(python list와 numpy array의 내부 구현 비교)

![Integer Memory Layout](../images/numpy/cint_vs_pyint.png)

![Array Memory Layout](../images/numpy/array_vs_list.png)

<small> (Referenced by Data Science Handbook) </small>

**5) numpy array는 universal function(through broadcast)를 제공하기 때문에 같은 연산 반복에 대해 훨씬 빠르다. 데이터의 크기가 클수록 차이가 더 크다.**

- 아래는 big_array라는 1000000개의 원소를 가지는 array를 만든 뒤에 for문을 돌면서 각 원소를 뒤집는 연산을 했을 때의 걸리는 시간과, numpy array에 있는 UFuncs(Universal function)을 사용했을 때 걸리는 시간을 측정한 것이다.


- 거의 1000배정도 차이가 나는 것을 볼 수 있다.

![speed_comparison](../images/numpy/list_vs_nparray.png)

# 2. Numpy Basics 

- numpy의 기본적인 사용법에 대해서 배워봅니다.


- numpy에서 numpy.array를 만드는 여러가지 방법과 지원하는 연산자에 대해서 공부합니다.

## 2.1 Numpy array Creation

In [1]:
# numpy 라이브러리를 불러옵니다.
import numpy as np

In [8]:
# 파이썬 리스트 선언
data = [1, 2, 3, 4, 5]
data, type(data)

([1, 2, 3, 4, 5], list)

In [4]:
# 파이썬 2차원 리스트(행렬) 선언
data2 = [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
        ]
data2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
# 파이썬 list를 numpy array로 변환합니다.
data = np.array(data)
data, data.shape
# numpy array를 만드는 방식의 대부분은 파이썬 리스트를 np.array로 변환하는 방식입니다.
# np.array([1, 2, 3, 4, 5])
# np.array.shape은 np.array의 크기를 알려줍니다.

(array([1, 2, 3, 4, 5]), (5,))

In [11]:
# 2차원 리스트를 np.array로 만듭니다.
data2 = np.array(data2)
data2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr2.shape
# arr2의 차원 
# arr2의 행, 열의 크기
# arr2의 행 x 열
# arr2의 원소의 타입.
# arr2의 원소의 사이즈(bytes)
# itemsize * size

(3, 3)

## 2.2 Array Initialization 

- numpy array를 초기값과 함께 생성하는 방법도 있습니다.


- 원소가 0인 array를 생성하는 np.zeros()

- 원소가 1인 array를 생성하는 np.ones()

- 특정 범위의 원소를 가지는 np.arange()

In [12]:
# 0이 5개 있는 array
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [13]:
# 0이 3x3인 array
arr = np.zeros((3, 3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# 1이 3개 있는 array
arr = np.ones(3)
arr

array([1., 1., 1.])

In [15]:
# 1이 2x2인 array
arr = np.ones((2, 2))
arr

array([[1., 1.],
       [1., 1.]])

In [21]:
# 0부터 9까지 숫자를 자동으로 생성한 array
arr = np.random.randint(9)
arr

4

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# 10부터 99까지 숫자를 자동으로 생성한 array
arr = np.random.randint(10, 99)
arr

86

In [24]:
np.arange(10, 100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

## 2.3. Array Operation (like vector) --> Universal Function

- numpy array를 쓰는 가장 큰 이유는 vector처럼 사용할 수 있기 때문입니다.


- 그렇기 때문에 scipy, matplotlib, scikit-learn, pandas, tensorflow, pytorch 등 대부분의 데이터분석 라이브러리들이 numpy array를 사용합니다.


- 데이터 분석은 99.9% 데이터를 벡터로 표현하여 분석하기 때문에, 이 특징은 ***굉장히*** 중요합니다.

![Vector operation](../images/numpy/vector_operations.png)

- 두 벡터 A = (1, 2), B = (2, 1)이라고 할 때, 벡터의 연산은 다음과 같이 정의됩니다.

A + B = (3, 3)


A - B = (1, -1)


A o B = 1x2 + 2x1 = 4 (dot product)

![Vector product](../images/numpy/vector_product.png)

In [25]:
# v1 = (1, 2, 3), v2 = (4, 5, 6) 벡터 2개 생성하기.
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [27]:
list(v1) + list(v2)

[1, 2, 3, 4, 5, 6]

In [10]:
# 리스트로 더하기 연산해보기

[1, 2, 3, 4, 5, 6]

In [28]:
#  vector addition
v1 + v2

array([5, 7, 9])

In [29]:
#  vector subtraction
v1 - v2

array([-3, -3, -3])

In [30]:
# (not vector operation) elementwise multiplication
v1 * v2

array([ 4, 10, 18])

In [32]:
# (not vector operation) elementwise division
v1 / v2

array([0.25, 0.4 , 0.5 ])

In [33]:
# dot product
np.dot(v1, v2)

32

In [34]:
v1 @ v2

32

## 2.4. Broadcast

- 서로 크기가 다른 numpy array를 연산할 때, 자동으로 연산을 전파(broadcast)해주는 기능. 행렬곱 연산을 할 때 편리하다.

In [35]:
arr1 = np.array([[1, 2, 3,],
               [4, 5, 6]])

In [36]:
arr1.shape

(2, 3)

In [37]:
arr2 = np.array([7, 8, 9])

In [38]:
arr2.shape

(3,)

In [39]:
# 2개의 array를 더해보면?
arr1 + arr2

array([[ 8, 10, 12],
       [11, 13, 15]])

In [40]:
# 2개의 array를 곱해보면? (**)
arr1 * arr2

array([[ 7, 16, 27],
       [28, 40, 54]])

In [41]:
# arr1에 10을 곱해보면?
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [44]:
# arr1을 제곱해보면?
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

## 2.5. Universal Functions 

- numpy array는 하나의 함수를 모든 원소에 자동으로 적용해주는 Universal Function이라는 기능을 제공한다. 이 덕분에 모든 원소에 대해 같은 작업을 처리할 때 엄청나게 빠른 속도를 낼 수 있다.

In [45]:
arr1 = np.array([1, 2, 3])
arr1 / 1

array([1., 2., 3.])

In [46]:
# 모든 원소를 역수를 취하려면 어떻게 해야할까?
1 / arr1

array([1.        , 0.5       , 0.33333333])

In [47]:
# 모든 원소에 2를 더하려면 어떻게 해야할까?
arr1 + 2

array([3, 4, 5])

## 2.6. Indexing (same as python list) 

In [48]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
# 첫번째 원소
arr1[0]

0

In [51]:
# 마지막 원소
arr1[-1]

9

In [52]:
# 앞에서부터 원소 3개 slicing
arr1[:3]

array([0, 1, 2])

In [53]:
arr2 = np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
# arr2의 2, 3 원소
arr2[1, 2]

7

In [55]:
# arr2의 세번째 column
arr2[:, 2]

array([ 3,  7, 11])

In [56]:
# arr2의 두번째 row
arr2[1, :]

array([5, 6, 7, 8])

## 2.7. Masking 

In [57]:
mask = np.array([1, 0, 0, 1, 1, 0, 0])

In [58]:
data = np.random.randn(7, 4)
data

array([[ 0.75015357,  0.20496923, -0.0530142 , -1.88975351],
       [ 0.68175027, -0.57953472,  0.5402062 ,  0.42646233],
       [-0.06813667, -1.06449623, -1.19785255,  0.55796335],
       [ 0.73684406, -0.88296561,  0.18811697, -0.29024191],
       [ 0.18876991, -1.20816619, -0.73606568, -0.45641369],
       [ 1.29159595, -1.31830216, -0.00853118, -0.10734884],
       [ 2.98316828, -0.6910342 , -0.90680045, -0.02395645]])

In [59]:
data.shape

(7, 4)

In [60]:
# mask 만들기
masking = (mask == 1)
masking

array([ True, False, False,  True,  True, False, False])

In [61]:
# 위에서 생성한 data에 mask를 적용해본다.
data[masking]

array([[ 0.75015357,  0.20496923, -0.0530142 , -1.88975351],
       [ 0.73684406, -0.88296561,  0.18811697, -0.29024191],
       [ 0.18876991, -1.20816619, -0.73606568, -0.45641369]])

In [62]:
# 마스크를 0으로 바꿔본다.
data[masking == 0]

array([[ 0.68175027, -0.57953472,  0.5402062 ,  0.42646233],
       [-0.06813667, -1.06449623, -1.19785255,  0.55796335],
       [ 1.29159595, -1.31830216, -0.00853118, -0.10734884],
       [ 2.98316828, -0.6910342 , -0.90680045, -0.02395645]])

In [ ]:
# fancy indexing을 이용해서 masking
# 첫번째 column에서 0 이하인 원소를 가지는 row를 출력하고 싶습니다.

In [63]:
# 1) 첫번째 column을 뽑습니다.
data[:, 0]

array([ 0.75015357,  0.68175027, -0.06813667,  0.73684406,  0.18876991,
        1.29159595,  2.98316828])

In [65]:
# 2) 첫번째 column에서 0 이하인 원소가 어디에 있는지 확인합니다.
data[:, 0] <= 0

array([False, False,  True, False, False, False, False])

In [66]:
# 3) 확인된 위치에 있는 row를 출력합니다.
data[data[:, 0] <= 0]

array([[-0.06813667, -1.06449623, -1.19785255,  0.55796335]])

In [67]:
# fancy indexing의 또 다른 방법
data[data[:, 0]<0, 0]

array([-0.06813667])

In [68]:
data[data[:, 0]<0, 0] = 0
data

array([[ 0.75015357,  0.20496923, -0.0530142 , -1.88975351],
       [ 0.68175027, -0.57953472,  0.5402062 ,  0.42646233],
       [ 0.        , -1.06449623, -1.19785255,  0.55796335],
       [ 0.73684406, -0.88296561,  0.18811697, -0.29024191],
       [ 0.18876991, -1.20816619, -0.73606568, -0.45641369],
       [ 1.29159595, -1.31830216, -0.00853118, -0.10734884],
       [ 2.98316828, -0.6910342 , -0.90680045, -0.02395645]])

In [70]:
data[data < 0] = 0
data

array([[0.75015357, 0.20496923, 0.        , 0.        ],
       [0.68175027, 0.        , 0.5402062 , 0.42646233],
       [0.        , 0.        , 0.        , 0.55796335],
       [0.73684406, 0.        , 0.18811697, 0.        ],
       [0.18876991, 0.        , 0.        , 0.        ],
       [1.29159595, 0.        , 0.        , 0.        ],
       [2.98316828, 0.        , 0.        , 0.        ]])

## 2.8. Numpy Methods 

In [71]:
# 표준정규분포에서 random sampling을 한 원소를 가지는 5x3 행렬을 만든다.
mat1 = np.random.randn(5, 3)
mat1

array([[ 9.79758039e-03,  7.42997695e-01,  1.04918159e+00],
       [-1.24102418e+00,  4.42354272e-01, -9.29836854e-01],
       [-5.23627664e-01,  6.27721672e-01,  2.38828631e-01],
       [ 2.17369646e-01, -1.57577457e+00, -6.63173060e-01],
       [-2.09883176e-01, -1.27048066e+00, -1.18616347e-03]])

In [72]:
# mat1에 절대값 씌우기
np.abs(mat1)

array([[9.79758039e-03, 7.42997695e-01, 1.04918159e+00],
       [1.24102418e+00, 4.42354272e-01, 9.29836854e-01],
       [5.23627664e-01, 6.27721672e-01, 2.38828631e-01],
       [2.17369646e-01, 1.57577457e+00, 6.63173060e-01],
       [2.09883176e-01, 1.27048066e+00, 1.18616347e-03]])

In [73]:
# mat1의 square root(제곱급) 구하기
# imagnary numbers = nan
np.sqrt(mat1)

<ipython-input-73-6112d96785bf>:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(mat1)


array([[0.09898273, 0.86197314, 1.02429565],
       [       nan, 0.66509719,        nan],
       [       nan, 0.79228888, 0.48870096],
       [0.46622918,        nan,        nan],
       [       nan,        nan,        nan]])

In [74]:
# mat1 제곱하기
mat1**2

array([[9.59925814e-05, 5.52045575e-01, 1.10078200e+00],
       [1.54014101e+00, 1.95677302e-01, 8.64596576e-01],
       [2.74185931e-01, 3.94034498e-01, 5.70391150e-02],
       [4.72495628e-02, 2.48306551e+00, 4.39798507e-01],
       [4.40509477e-02, 1.61412110e+00, 1.40698378e-06]])

In [75]:
# mat1 제곱하기
np.square(mat1)

array([[9.59925814e-05, 5.52045575e-01, 1.10078200e+00],
       [1.54014101e+00, 1.95677302e-01, 8.64596576e-01],
       [2.74185931e-01, 3.94034498e-01, 5.70391150e-02],
       [4.72495628e-02, 2.48306551e+00, 4.39798507e-01],
       [4.40509477e-02, 1.61412110e+00, 1.40698378e-06]])

In [76]:
# mat1의 지수값 구하기
np.exp(mat1)

array([[1.00984573, 2.10222792, 2.85531333],
       [0.28908799, 1.55636702, 0.39461809],
       [0.59236773, 1.87333764, 1.26976092],
       [1.24280341, 0.20684727, 0.51521393],
       [0.81067895, 0.28069667, 0.99881454]])

In [77]:
# mat의 log값(자연로그) 구하기
# log의 밑이 음수가 될 수 없다. (자연로그)
np.log(mat1)

<ipython-input-77-6518b5e6440b>:3: RuntimeWarning: invalid value encountered in log
  np.log(mat1)


array([[-4.62561982, -0.29706234,  0.04801042],
       [        nan, -0.8156442 ,         nan],
       [        nan, -0.46565841, -1.43200901],
       [-1.52615594,         nan,         nan],
       [        nan,         nan,         nan]])

In [78]:
# 상용로그
np.log10(mat1)

<ipython-input-78-a091af1a621d>:2: RuntimeWarning: invalid value encountered in log10
  np.log10(mat1)


array([[-2.00888116, -0.12901253,  0.02085066],
       [        nan, -0.35422977,         nan],
       [        nan, -0.20223288, -0.62191361],
       [-0.6628011 ,         nan,         nan],
       [        nan,         nan,         nan]])

In [79]:
# 이진로그
np.log2(mat1)

<ipython-input-79-09f0ec8234cb>:2: RuntimeWarning: invalid value encountered in log2
  np.log2(mat1)


array([[-6.67335878, -0.42857036,  0.06926439],
       [        nan, -1.17672584,         nan],
       [        nan, -0.67180308, -2.0659523 ],
       [-2.2017776 ,         nan,         nan],
       [        nan,         nan,         nan]])

In [80]:
# 부호찾기
np.sign(mat1)

array([[ 1.,  1.,  1.],
       [-1.,  1., -1.],
       [-1.,  1.,  1.],
       [ 1., -1., -1.],
       [-1., -1., -1.]])

In [81]:
# 올림
np.ceil(mat1)

array([[ 1.,  1.,  2.],
       [-1.,  1., -0.],
       [-0.,  1.,  1.],
       [ 1., -1., -0.],
       [-0., -1., -0.]])

In [82]:
# 내림
np.floor(mat1)

array([[ 0.,  0.,  1.],
       [-2.,  0., -1.],
       [-1.,  0.,  0.],
       [ 0., -2., -1.],
       [-1., -2., -1.]])

In [83]:
# 0인지 아닌지
np.isnan(mat1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [84]:
np.isnan(np.log(mat1))

<ipython-input-84-cb2ae9d6dc08>:1: RuntimeWarning: invalid value encountered in log
  np.isnan(np.log(mat1))


array([[False, False, False],
       [ True, False,  True],
       [ True, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [85]:
np.isinf(mat1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [86]:
np.sin(mat1)

array([[ 0.00979742,  0.67649858,  0.86701572],
       [-0.94611615,  0.42806831, -0.8015224 ],
       [-0.50002502,  0.58730228,  0.23656467],
       [ 0.21566191, -0.99998761, -0.61562045],
       [-0.20834564, -0.95524315, -0.00118616]])

In [87]:
np.cos(mat1)

array([[ 0.999952  ,  0.73644393,  0.49828079],
       [ 0.32382746,  0.90374638,  0.59796476],
       [ 0.86601096,  0.80936767,  0.97161575],
       [ 0.97646809, -0.00497823,  0.7880428 ],
       [ 0.97805526,  0.29582176,  0.9999993 ]])

In [88]:
np.tan(mat1)

array([[ 9.79789390e-03,  9.18601608e-01,  1.74001432e+00],
       [-2.92166742e+00,  4.73659784e-01, -1.34041746e+00],
       [-5.77388788e-01,  7.25631004e-01,  2.43475540e-01],
       [ 2.20859152e-01,  2.00872241e+02, -7.81201799e-01],
       [-2.13020317e-01, -3.22911723e+00, -1.18616403e-03]])

In [89]:
np.tanh(mat1)

array([[ 0.00979727,  0.63095288,  0.78148797],
       [-0.84574744,  0.41559399, -0.73051782],
       [-0.480495  ,  0.55648142,  0.23438904],
       [ 0.2140096 , -0.91793944, -0.5804712 ],
       [-0.20685468, -0.85392787, -0.00118616]])

In [90]:
mat2 = np.random.randn(5, 3)
mat2

array([[ 1.25541141, -0.50056893,  0.38217263],
       [-0.65681506, -0.48626574, -0.88669427],
       [ 0.46343782,  1.01809396,  0.07145997],
       [-1.18441875,  0.27931988, -1.31695118],
       [ 0.51131577,  0.66150663,  0.52995659]])

In [91]:
np.maximum(mat1, mat2)

array([[ 1.25541141,  0.74299769,  1.04918159],
       [-0.65681506,  0.44235427, -0.88669427],
       [ 0.46343782,  1.01809396,  0.23882863],
       [ 0.21736965,  0.27931988, -0.66317306],
       [ 0.51131577,  0.66150663,  0.52995659]])

## 2.9. Reshaping array

In [92]:
x = np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
# x1를 3x3 행렬로 변형합니다.
x1 = np.arange(9)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [97]:
x1 = x1.reshape(3, 3)
x1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [98]:
x == x1

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [102]:
# (1, 2, 3)을 transpose 해봅니다.
x = np.array([1, 2, 3])
x.reshape(3, 1)

array([[1],
       [2],
       [3]])

## 2.10. Concatenation of arrays

In [103]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# arr1와 arr2를 합칩니다
# arr1 + arr2?

array([5, 7, 9])

In [105]:
# stacking vertically
np.stack([arr1, arr2])

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
# stacking vertically
np.vstack([arr1, arr2])

array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
# stacking horizontally
np.hstack([arr1, arr2])

array([1, 2, 3, 4, 5, 6])

## 2.10. Aggregation functions 

In [108]:
mat1

array([[ 9.79758039e-03,  7.42997695e-01,  1.04918159e+00],
       [-1.24102418e+00,  4.42354272e-01, -9.29836854e-01],
       [-5.23627664e-01,  6.27721672e-01,  2.38828631e-01],
       [ 2.17369646e-01, -1.57577457e+00, -6.63173060e-01],
       [-2.09883176e-01, -1.27048066e+00, -1.18616347e-03]])

In [109]:
np.sum(mat1)

-3.0867352434695587

In [110]:
# 다른 축으로 더해보기
np.sum(mat1, axis=0)

array([-1.74736779, -1.03318159, -0.30618586])

In [111]:
# 다른 축으로 더해보기
np.sum(mat1, axis=1)

array([ 1.80197686, -1.72850676,  0.34292264, -2.02157799, -1.48155   ])

In [112]:
# 평균
np.mean(mat1)

-0.20578234956463726

In [113]:
mat3 = np.random.rand(5, 3)
mat3

array([[0.60251241, 0.18773257, 0.93469525],
       [0.80556427, 0.86147722, 0.51193372],
       [0.52331646, 0.37911291, 0.25237063],
       [0.33398846, 0.56545473, 0.5682    ],
       [0.615554  , 0.55324153, 0.82401842]])

In [114]:
np.mean(mat3)

0.5679448387383904

In [115]:
np.mean(mat3, axis=0)

array([0.57618712, 0.50940379, 0.61824361])

In [116]:
np.mean(mat3, axis=1)

array([0.57498008, 0.72632507, 0.38493333, 0.4892144 , 0.66427132])

In [117]:
np.std(mat3)

0.2138626157478123

In [118]:
np.min(mat3, axis=0)

array([0.33398846, 0.18773257, 0.25237063])

In [119]:
np.max(mat3, axis=1)

array([0.93469525, 0.86147722, 0.52331646, 0.5682    , 0.82401842])

In [121]:
# 최소값이 있는 Index
np.argmin(mat3, axis=0)

array([3, 0, 2])

In [122]:
# 최대값이 있는 Index
np.argmax(mat3, axis=0)

array([1, 1, 0])

In [124]:
mat3

array([[0.60251241, 0.18773257, 0.93469525],
       [0.80556427, 0.86147722, 0.51193372],
       [0.52331646, 0.37911291, 0.25237063],
       [0.33398846, 0.56545473, 0.5682    ],
       [0.615554  , 0.55324153, 0.82401842]])

In [123]:
np.cumsum(mat3)

array([0.60251241, 0.79024498, 1.72494023, 2.5305045 , 3.39198172,
       3.90391545, 4.42723191, 4.80634482, 5.05871544, 5.3927039 ,
       5.95815863, 6.52635863, 7.14191263, 7.69515416, 8.51917258])

In [125]:
np.cumsum(mat3, axis=1)

array([[0.60251241, 0.79024498, 1.72494023],
       [0.80556427, 1.66704149, 2.17897522],
       [0.52331646, 0.90242937, 1.15479999],
       [0.33398846, 0.89944319, 1.46764319],
       [0.615554  , 1.16879553, 1.99281395]])

In [126]:
np.cumprod(mat3, axis=0)

array([[0.60251241, 0.18773257, 0.93469525],
       [0.48536246, 0.16172734, 0.47850202],
       [0.25399816, 0.06131292, 0.12075986],
       [0.08483246, 0.03466968, 0.06861575],
       [0.05221896, 0.01918071, 0.05654064]])

In [127]:
# 그냥 정렬
np.sort(mat3, axis=0)

array([[0.33398846, 0.18773257, 0.25237063],
       [0.52331646, 0.37911291, 0.51193372],
       [0.60251241, 0.55324153, 0.5682    ],
       [0.615554  , 0.56545473, 0.82401842],
       [0.80556427, 0.86147722, 0.93469525]])

In [128]:
# index를 정렬
np.argsort(mat3, axis=0)

array([[3, 0, 2],
       [2, 2, 1],
       [0, 4, 3],
       [4, 3, 4],
       [1, 1, 0]])

## 3. Powerful Numpy 

- 맨 처음에도 봤듯이 numpy는 파이썬 리스트에 비해 연산이 빠릅니다.


- 직접 실험을 통해 그 차이를 확인해보겠습니다.

In [21]:
np.random.seed(0)

def reverse_num(values):
    output = np.empty(len(values))
    
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    
    return output

In [25]:
# 1부터 100까지 범위에서 1000000개를 랜덤으로 뽑아서 array를 만듭니다.
big_array = np.random.randint(1, 100, size=10000000)

In [26]:
%timeit reverse_num(big_array)

17.5 s ± 370 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [27]:
%timeit 1.0 / big_array

26.7 ms ± 583 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Q. 왜 numpy가 파이썬(정확히는 CPython)으로 구현한 함수를 통해 반복문을 수행한것보다 빠를까?

A. 매번 반복할 때마다 ***"type matching"*** 과 ***"function dispatching"*** 을 파이썬 interpreter가 수행하기 때문에 **"performance bottleneck"** 이 생깁니다.