In [7]:
from sklearn.datasets import load_iris
import numpy as np

In [6]:
iris = load_iris()
iris.data[0:2, :]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [9]:
x1 = np.array([[5.1], [3.5], [1.4], [0.2]])
x2 = np.array([[4.9], [3.0], [1.4], [0.2]])

print(x1)
print(x2)

[[5.1]
 [3.5]
 [1.4]
 [0.2]]
[[4.9]
 [3. ]
 [1.4]
 [0.2]]


In [15]:
X = np.array(iris.data[0:2, :])
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [16]:
X.T

array([[5.1, 4.9],
       [3.5, 3. ],
       [1.4, 1.4],
       [0.2, 0.2]])

### inner product

In [17]:
x = np.array([[1], [2], [3]])
y = np.array([[4], [5], [6]])

In [18]:
x.T @ y

array([[32]])

In [20]:
np.dot(x.T, y)

array([[32]])

In [21]:
#practice

stock_price = np.array([[100], [80], [50]])
stock_count = np.array([[3], [4], [5]])

np.dot(stock_count.T, stock_price)

array([[870]])

In [1]:
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt

In [4]:
digits = load_digits()
d1 = digits.images[0]
d2 = digits.images[10]
d3 = digits.images[1]
d4 = digits.images[11]

v1 = d1.reshape(64, 1)
v2 = d2.reshape(64, 1)
v3 = d3.reshape(64, 1)
v4 = d4.reshape(64, 1)

In [7]:
import numpy as np
print(np.dot(v1.T, v2), np.dot(v1.T, v3))

[[3064.]] [[1866.]]


In [10]:
digits.images[0].reshape(64, 1).T @ digits.images[9].reshape(64, 1)

array([[2807.]])